title = "LZC"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/lexingtonzencenter/"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/fm-sky.jpg"
  recent_posts_number = 2
  cover_dimming_class = "bg-black-50"
  custom_css = "custom.css"


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "post"
  name = "Articles"
  url = "/post/"
  weight = 3  

[[menu.main]]
  identifier = "parent"
  name = "Parent"
  url = "#"
  weight = 3.5

[[menu.main]]
  identifier = "child1"
  name = "Child 1"
  parent = "parent"
  url = "/child-1/"
  weight = 1  

[[menu.main]]
  identifier = "child2"
  name = "Child 2"
  parent = "parent"
  url = "/child-2/"
  weight = 2  
  
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 4  

