title = "LZC"
baseURL = "https://lzchugo.netlify.app"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/lexingtonzencenter/"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/fm-sky.jpg"
  recent_posts_number = 2
  cover_dimming_class = "bg-black-00"
  site_header_text_background_color = "rgba(50, 50, 50, 0.7);"
  page_header_text_background_color = "rgba(50, 50, 50, 0.7)"

[markup.goldmark.renderer]
  unsafe = true


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#"
  weight = 2

[[menu.main]]
  identifier = "center"
  name = "The Center"
  parent = "about"
  url = "/center/"
  weight = 1  

[[menu.main]]
  identifier = "teachers"
  name = "Teachers"
  parent = "about"
  url = "/teachers/"
  weight = 2 

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  parent = "about"
  url = "/contact/"
  weight = 3 

[[menu.main]]
  identifier = "post"
  name = "Articles"
  url = "/post/"
  weight = 3 

[[menu.main]]
  identifier = "more"
  name = "Resources"
  url = "#"
  weight = 3 

[[menu.main]]
  identifier = "sits"
  name = "Services"
  parent = "more"
  url = "/sits/"
  weight = 1

[[menu.main]]
  identifier = "sitting"
  name = "Sitting"
  parent = "more"
  url = "/sitting/"
  weight = 2

[[menu.main]]
  identifier = "resources"
  name = "Reading"
  parent = "more"
  url = "/reading/"
  weight = 3

[[menu.main]]  
  identifier = "donate"
  name = "Donate"
  url = "/donate/"
  weight = 5

