[context.production.environment]
  HUGO_VERSION = "0.73.0"
  # uncomment the following when we are ready:
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo  -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"