backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: post
    label: "Articles"
    folder: content/post
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", defaut: "An Awesome Dharma Talk"}
      - {label: "Date", name: "date", widget: "datetime" }
      - {label: "Description", name: "description", widget: "string", defaut: "Offered by Prince on December 31, 1999", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", default: "/images/notebook.jpg", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["zen"], required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: page
    label: "Pages"
    folder: content
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Omit Text from the Header", name: "omit_header_text", widget: "boolean"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}





